[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "packaging",

    "numpy==1.22.4",
    "torch-mlir>=20221022.634",
    "iree-compiler>=20221022.190",
    "iree-runtime>=20221022.190",
]
build-backend = "setuptools.build_meta"
